project:
  type: default
  output-dir: pdf
  render:
    - lectures/*.qmd

execute:
  echo: true
  warning: false
  message: false

lang: ru

format:
  beamer:
    pdf-engine: xelatex
    classoption: 10pt
    slide-level: 2
    aspectratio: 169
    theme: Dresden
    colortheme: dolphin
    keep-tex: true
    include-in-header: styles/macros.tex

